### ISSUE TITLE
java.lang.IllegalArgumentException: Software rendering doesn't support hardware bitmaps

### ISSUE THREAD

**Issue by AnthonyKoueik** [Dimezis/BlurView#109]
1) 1.6.1

2) Galaxy S8 - OS Version: 9

3) when I pop backstack a fragment

4)  <eightbitlab.com.blurview.BlurView
        android:id="@+id/bottom_nav_bar_blurView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:blurOverlayColor="@color/colorTransparentWhite9">

5) java.lang.IllegalArgumentException: Software rendering doesn't support hardware bitmaps
        at android.graphics.BaseCanvas.onHwBitmapInSwMode(BaseCanvas.java:550)
        at android.graphics.BaseCanvas.throwIfHwBitmapInSwMode(BaseCanvas.java:557)
        at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:69)
        at android.graphics.BaseCanvas.drawBitmap(BaseCanvas.java:127)
        at android.graphics.Canvas.drawBitmap(Canvas.java:1504)
        at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:545)
        at android.widget.ImageView.onDraw(ImageView.java:1342)
        at android.view.View.draw(View.java:20207)
        at android.view.View.draw(View.java:20077)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.ViewOverlay$OverlayViewGroup.dispatchDraw(ViewOverlay.java:251)
        at android.view.View.draw(View.java:20210)
        at android.view.View.buildDrawingCacheImpl(View.java:19475)
        at android.view.View.buildDrawingCache(View.java:19338)
        at android.view.View.draw(View.java:19927)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:2023)
        at android.view.View.draw(View.java:20210)
        at android.view.View.draw(View.java:20077)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.draw(View.java:20210)
        at eightbitlab.com.blurview.BlockingBlurController.updateBlur(BlockingBlurController.java:144)
        at eightbitlab.com.blurview.BlockingBlurController$1.onPreDraw(BlockingBlurController.java:59)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:977)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2474)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:696)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by Dimezis** [comment]
Probably an image loading library you use (Glide, possibly) has decoded some image with hardware configuration. The canvas I use can't work with hardware bitmaps, so there's not much I can do.

I can't even `try-catch` it, because the drawing is scheduled in a separate looper message by the system.

For now, you can try to disable hardware bitmaps, meanwhile, I'll think if anything can be done

**Comment by AnthonyKoueik** [comment]
Yes Glide you are right ! 
I will see check where we are using the hardware bitmaps

10x

**Comment by AnthonyKoueik** [comment]
cant it be related because to the vector drawable ?
we are using a vector when setting the drawable 

`   <ImageView
                    android:id="@+id/ic_nav_bar_home"
                    android:layout_width="@dimen/nav_bar_icon_size"
                    android:layout_height="@dimen/nav_bar_icon_size"
                    android:layout_marginStart="15dp"
                    android:layout_marginEnd="15dp"
                    android:scaleType="fitCenter"
                    android:src="@drawable/ic_home_thin" />
`

**Comment by Dimezis** [comment]
> I will see check where we are using the hardware bitmaps

I believe it's used automatically there, so you need to opt in to disable it.
https://bumptech.github.io/glide/doc/hardwarebitmaps.html

> cant it be related to the vector drawable ?

I don't think so, but I'm not sure, so better check it

**Comment by AnthonyKoueik** [comment]
Hello 

I have removed all my images inside the BlurView and it is still crashing with the same exception.

my flow is that I'm committing fragments and then when I'm poping all the fragment -> the crash happens 

when i use supportFragmentManager.popBackStackImmediate() 
the crash disappear   
but when I use  supportFragmentManager.popBackStack()
the crash occurs

hope this can give you any clue

**Comment by Dimezis** [comment]
The stacktrace says it's crashing during ImageView drawing, so if you removed ALL images, the stacktrace should be different?

**Comment by AnthonyKoueik** [comment]
hello

yep ! it's pretty much the same exception.

```
java.lang.IllegalArgumentException: Software rendering doesn't support hardware bitmaps
        at android.graphics.BaseCanvas.onHwBitmapInSwMode(BaseCanvas.java:550)
        at android.graphics.BaseCanvas.throwIfHwBitmapInSwMode(BaseCanvas.java:557)
        at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:69)
        at android.graphics.BaseCanvas.drawBitmap(BaseCanvas.java:127)
        at android.graphics.Canvas.drawBitmap(Canvas.java:1504)
        at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:545)
        at android.widget.ImageView.onDraw(ImageView.java:1342)
        at android.view.View.draw(View.java:20207)
        at android.view.View.draw(View.java:20077)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.ViewOverlay$OverlayViewGroup.dispatchDraw(ViewOverlay.java:251)
        at android.view.View.draw(View.java:20210)
        at android.view.View.buildDrawingCacheImpl(View.java:19475)
        at android.view.View.buildDrawingCache(View.java:19338)
        at android.view.View.draw(View.java:19927)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:2023)
        at android.view.View.draw(View.java:20210)
        at android.view.View.draw(View.java:20077)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.draw(View.java:20210)
        at eightbitlab.com.blurview.BlockingBlurController.updateBlur(BlockingBlurController.java:145)
        at eightbitlab.com.blurview.BlockingBlurController$1.onPreDraw(BlockingBlurController.java:61)
```

**Comment by Dimezis** [comment]
But you still have an ImageView in the stacktrace, so you probably didn't remove all the ImageViews

**Comment by AnthonyKoueik** [comment]
Sorry for the delay.
I'm pretty sure that i have no Imageview anymore.
That's the weird case.

**Comment by necatisozer** [comment]
I had that issue with Coil. When I set `allowHardware` to `false`, crash disappeared.

**Comment by vellrya** [comment]
I apologise for bringing up an old issue. Same crash on ver. 2.0.4

```
Galaxy Note10 Lite (Android 11)
Fatal Exception: java.lang.IllegalArgumentException: Software rendering doesn't support hardware bitmaps
       at android.graphics.BaseCanvas.onHwBitmapInSwMode(BaseCanvas.java:673)
       at android.graphics.BaseCanvas.throwIfHwBitmapInSwMode(BaseCanvas.java:680)
       at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:84)
       at android.graphics.BaseCanvas.drawBitmap(BaseCanvas.java:142)
       at android.graphics.Canvas.drawBitmap(Canvas.java:1648)
       at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:548)
       at android.widget.ImageView.onDraw(ImageView.java:1435)
       at android.view.View.draw(View.java:23901)
       at android.view.View.draw(View.java:23773)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
       at android.view.ViewOverlay$OverlayViewGroup.dispatchDraw(ViewOverlay.java:254)
       at android.view.View.draw(View.java:23916)
       at eightbitlab.com.blurview.PreDrawBlurController.updateBlur(PreDrawBlurController.java:120)
       at eightbitlab.com.blurview.PreDrawBlurController$1.onPreDraw(PreDrawBlurController.java:51)
       at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1124)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3854)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2618)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9971)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010)
       at android.view.Choreographer.doCallbacks(Choreographer.java:809)
       at android.view.Choreographer.doFrame(Choreographer.java:744)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8633)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

```
Galaxy A41 (Android 11)
Fatal Exception: java.lang.IllegalArgumentException: Software rendering doesn't support hardware bitmaps
       at android.graphics.BaseCanvas.onHwBitmapInSwMode(BaseCanvas.java:673)
       at android.graphics.BaseCanvas.throwIfHwBitmapInSwMode(BaseCanvas.java:680)
       at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:84)
       at android.graphics.BaseCanvas.drawBitmap(BaseCanvas.java:142)
       at android.graphics.Canvas.drawBitmap(Canvas.java:1648)
       at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:548)
       at android.widget.ImageView.onDraw(ImageView.java:1435)
       at android.view.View.draw(View.java:23901)
       at android.view.View.draw(View.java:23773)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
       at android.view.ViewOverlay$OverlayViewGroup.dispatchDraw(ViewOverlay.java:254)
       at android.view.View.draw(View.java:23916)
       at eightbitlab.com.blurview.PreDrawBlurController.updateBlur(PreDrawBlurController.java:120)
       at eightbitlab.com.blurview.PreDrawBlurController$1.onPreDraw(PreDrawBlurController.java:51)
       at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1124)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3854)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2618)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9965)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010)
       at android.view.Choreographer.doCallbacks(Choreographer.java:809)
       at android.view.Choreographer.doFrame(Choreographer.java:744)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8512)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)
```

I use Glide to load images, your link above shows that hardware bitmap should be disabled by default (and I haven't explicitly enabled it)

**Comment by Dimezis** [comment]
As I said, there's nothing I can do.
Don't use hardware bitmaps when there's a BlurView in the hierarchy

**Comment by vellrya** [comment]
![image](https://github.com/Dimezis/BlurView/assets/13716114/1710557f-ec45-43cc-9e53-b1c0d2a57b6e)

Any chance there will be a fix (possibly with an additional flag, but I don't think anyone wants crashes) that prevents crashes and just doesn't blur?

In the absolute majority of cases everything works normally, but on some devices this error occurs (although the image loading configuration used is identical on all phones).

**Comment by Dimezis** [comment]
@vellrya PRs are welcome

**Comment by auhah** [comment]
Setting the **android:elevation** property for views near blurView on Xiaomi devices causes a crash to occur.
