### ISSUE TITLE
NullPointerException 

### ISSUE THREAD

**Issue by ssadovnikov** [Dimezis/BlurView#11]
With RenderScript enable:
`java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v8.renderscript.RenderScript.validate()' on a null object reference
at android.support.v8.renderscript.BaseObj.getID(BaseObj.java:53)
at android.support.v8.renderscript.Script.setVar(Script.java:324)
at android.support.v8.renderscript.ScriptIntrinsicBlur.setRadius(ScriptIntrinsicBlur.java:89)
at eightbitlab.com.blurview.RenderScriptBlur.blur(RenderScriptBlur.java:60)
at eightbitlab.com.blurview.DefaultBlurController.blurAndSave(DefaultBlurController.java:233)
at eightbitlab.com.blurview.DefaultBlurController.drawBlurredContent(DefaultBlurController.java:216)
at eightbitlab.com.blurview.BlurView.draw(BlurView.java:57)`

Whit StackBlur enable:
`java.lang.NullPointerException: Attempt to get length of null array
at eightbitlab.com.blurview.StackBlur.blur(StackBlur.java:56)
at eightbitlab.com.blurview.DefaultBlurController.blurAndSave(DefaultBlurController.java:233)
at eightbitlab.com.blurview.DefaultBlurController.drawBlurredContent(DefaultBlurController.java:216)
at eightbitlab.com.blurview.BlurView.draw(BlurView.java:57)`

This issue occur every time when I use Fragments with custom animation for transactions.

**Comment by Dimezis** [comment]
Thanks for reporting. I'll investigate this issue.

**Comment by ssadovnikov** [comment]
I have figured out this issue.
`stopAutoBlurUpdate()` should be called in onDestroyView method before super.
I think you should add this info to "How to use" section.

**Comment by Dimezis** [comment]
Fixed in 1.1.0

**Comment by givod** [comment]
This error still occurs in version 1.2.0

**Comment by Dimezis** [comment]
@givod does it occur in 1.6.5 though?
