### ISSUE TITLE
IndexOutOfBoundsException when using BlurView in BaseAdapter

### ISSUE THREAD

**Issue by SourceEngine** [Dimezis/BlurView#118]
**Library Version:** 1.6.3
**Device and OS Version:** Samsung S10 (Android 10), also happens with other devices like Google Pixel, Motorola, Huawei...

**Detailed steps to reproduce the issue**
Populate a layout containing a BlurView with an Adapter. When the adapter contains only 1 item it is working as expected. When the adapter has more than 1 item it resolves in a java.lang.IndexOutOfBoundsException: Index: 1, Size: 0.

**BaseAdapter**

    @Override
    public int getCount() {
        return data.size();
    }

    @Override
    public Object getItem(int position) {
        return data.get(position);
    }

    @Override
    public long getItemId(int position) {
        return position;
    }

    @Override
    public View getView(final int position, View convertView, ViewGroup parent) {

        View v = convertView;
        if(v == null){
            v = activity.getLayoutInflater().inflate(R.layout.swipe_partner, parent, false);
        }
        

        // removing the Blur initilization removes the Exception
        BlurView blur_description = v.findViewById(R.id.blur_description);

        blur_description.setupWith(v.findViewById(R.id.parent))
                .setBlurAlgorithm(new RenderScriptBlur(context))
                .setBlurRadius(8f)
                .setHasFixedTransformationMatrix(true);

        BlurView blur_type = v.findViewById(R.id.blur_type);

        blur_type.setupWith(v.findViewById(R.id.parent))
                .setBlurAlgorithm(new RenderScriptBlur(context))
                .setBlurRadius(8f)
                .setHasFixedTransformationMatrix(true);
        return v;
    }

**Inflating Layout**
I have cropped the layout a bit to the important part. The layout shouldnt be the problem tho.
```
<LinearLayout
                android:id="@+id/parent"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_gravity="bottom"
                android:elevation="24dp"
                android:orientation="vertical">

                <androidx.cardview.widget.CardView
                    android:layout_width="wrap_content"
                    android:layout_height="match_parent"
                    android:layout_gravity="bottom"
                    android:layout_marginLeft="35dp"
                    android:layout_marginRight="35dp"
                    android:layout_marginBottom="8dp"
                    android:elevation="0dp"
                    app:cardBackgroundColor="@color/transperent"
                    app:cardCornerRadius="16dp"
                    app:cardElevation="24dp">

                    <eightbitlab.com.blurview.BlurView
                        android:id="@+id/blur_type"
                        android:layout_width="match_parent"
                        android:layout_height="match_parent"
                        app:blurOverlayColor="#66ffffff">

                        <LinearLayout
                            android:layout_width="match_parent"
                            android:layout_height="match_parent"
                            android:orientation="horizontal"
                            android:paddingTop="7dp"
                            android:paddingBottom="7dp">

                            <ImageView
                                android:layout_width="20dp"
                                android:layout_height="20dp"
                                android:layout_marginLeft="10dp"
                                android:layout_marginRight="5dp" />

                            <TextView
                                android:id="@+id/type"
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content"
                                android:layout_marginRight="10dp"
                                android:text="@string/dating"
                                android:textColor="?attr/colorTitle" />
                        </LinearLayout>

                    </eightbitlab.com.blurview.BlurView>
                </androidx.cardview.widget.CardView>

                <androidx.cardview.widget.CardView
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_gravity="bottom"
                    android:layout_marginLeft="35dp"
                    android:layout_marginRight="35dp"
                    android:layout_marginBottom="16dp"
                    android:elevation="0dp"
                    app:cardBackgroundColor="@color/transperent"
                    app:cardCornerRadius="16dp"
                    app:cardElevation="24dp">

                    <eightbitlab.com.blurview.BlurView
                        android:id="@+id/blur_description"
                        android:layout_width="match_parent"
                        android:layout_height="match_parent"
                        app:blurOverlayColor="#66ffffff">

                        <com.vanniktech.emoji.EmojiTextView
                            android:id="@+id/description"
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:layout_marginLeft="10dp"
                            android:layout_marginTop="7dp"
                            android:layout_marginRight="10dp"
                            android:layout_marginBottom="7dp"
                            android:textColor="?attr/colorTitle" />
                    </eightbitlab.com.blurview.BlurView>
                </androidx.cardview.widget.CardView>
            </LinearLayout>
```

**Stacktrace**

```
2020-07-20 19:17:22.359 7088-7088/com.Appname E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.Appname, PID: 7088
    java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
        at java.util.ArrayList.get(ArrayList.java:437)
        at android.view.ViewGroup.getAndVerifyPreorderedView(ViewGroup.java:4468)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4984)
        at android.view.View.draw(View.java:23060)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
        at android.view.View.draw(View.java:23060)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
        at android.view.View.draw(View.java:23060)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
        at android.view.View.buildDrawingCacheImpl(View.java:22456)
        at android.view.View.buildDrawingCache(View.java:22322)
        at android.view.View.draw(View.java:22912)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
        at android.view.View.draw(View.java:23193)
        at android.view.View.draw(View.java:23062)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
        at android.view.View.draw(View.java:23060)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
        at android.view.View.draw(View.java:23060)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
        at android.view.View.draw(View.java:23193)
        at eightbitlab.com.blurview.BlockingBlurController.updateBlur(BlockingBlurController.java:149)
        at eightbitlab.com.blurview.BlockingBlurController$1.onPreDraw(BlockingBlurController.java:61)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1102)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3310)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2200)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9065)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:999)
        at android.view.Choreographer.doCallbacks(Choreographer.java:797)
        at android.view.Choreographer.doFrame(Choreographer.java:732)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8016)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
```

If you need more information please let me know!
Thanks in advance!

**Comment by Dimezis** [comment]
I believe this crash has nothing to do with the library and happens in the ViewGroup, as the BlurView just requests the ViewGroup to draw itself on a software Canvas.
So you can report it to the Google issue tracker.

On a side note, you're misusing the ListView Adapter and the BlurView.

You should not do `findViewById` if `convertView` is not null. 
You also should not re-setup the BlurView if `convertView` is not null already. You'll waste a ton of resources to re-setup it on each scroll. It will lag as hell.

Also having even one BlurView in each list item is a huge performance hit, and you're using two.
Also `.setHasFixedTransformationMatrix()` should be set to false, as you're using it in the ListView.

At last, I don't know why you're still using the ListView instead of RecyclerView, but with RecyclerView this bug shouldn't happen, or at least it hasn't been reported with RecyclerView previously.

**Comment by SourceEngine** [comment]
> You should not do findViewById if convertView is not null.

True, this was a mistake while shrinking the code for only the relevant part.

> Also having even one BlurView in each list item is a huge performance hit, and you're using two.

Yes, but what you couldn't know, that this is **not** an `Adapter` for a `ListView`. Infact it is an `Adapter` for a `SwipeDeck` (my bad for not explaining well enougth)
Max 3 views are rendered at a time.

> At last, I don't know why you're still using the ListView instead of RecyclerView, but with RecyclerView this bug shouldn't happen, or at least it hasn't been reported with RecyclerView previously.

Also a fair point. This was due to the library i was using. Iam now using a different [Library](https://github.com/yuyakaido/CardStackView) using a `RecyclerView.Adapter`.
Sadly it has the same Exception: `java.lang.IndexOutOfBoundsException: Index: 1, Size: 0`

Should i still foreward it to Google?
Thank you for your time!

**Comment by Dimezis** [comment]
I'd still forward it, however, knowing Google, they might just say it's a library bug. 
So we'd need to create a minimal possible setup to replicate this bug.
If you could create a small repo with BlurView and CardStackView with the simplest layout you can make, I could then take care of the rest (meaning I could simplify the BlurView to just couple of lines of code and create an issue in Google Tracker)

**Comment by SourceEngine** [comment]
Okay, i will do it tomorrow

**Comment by SourceEngine** [comment]
Alright, so after making a new project with the most simple layout it suddenly worked. I think this exception happens when missusing the parent view. I migrated the layout structure to my existing project and after some tweaking also that one works now. Iam very sorry for wasting your time and ill close this "issue" now. Best regards!

**Comment by linsencc** [comment]
when use “ elevation” in xml can reproduce this issue.

same iusse: https://github.com/Kureev/react-native-blur/issues/397
