### ISSUE TITLE
Is it possible to blur each item in recyclerView?

### ISSUE THREAD

**Issue by greatkub** [Dimezis/BlurView#136]

**Comment by Dimezis** [comment]
Yes

**Comment by greatkub** [comment]
Could you give me the idea, please?

This is what I expected

    
<img width="582" alt="Screen Shot 2564-03-03 at 14 30 37" src="https://user-images.githubusercontent.com/71839217/109771208-1f938200-7c2f-11eb-9bce-a6cc03797706.png">

     I got this error message

          Caused by: java.lang.IllegalStateException: blurView_iv_item must not be null
        at com.example.consolereser.presentation.PurposeMeeting.PurposeMeetingActivity.onCreate(PurposeMeetingActivity.kt:34)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)

 This is my recyclerView_cell

     <?xml version="1.0" encoding="utf-8"?>
     <androidx.constraintlayout.widget.ConstraintLayout
     xmlns:android="http://schemas.android.com/apk/res/android"
     xmlns:tools="http://schemas.android.com/tools"
     android:layout_width="196dp"
     android:layout_height="wrap_content"
     xmlns:app="http://schemas.android.com/apk/res-auto">

    <androidx.constraintlayout.widget.ConstraintLayout
        android:id="@+id/constraintBlurviewItem"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginEnd="51dp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent">

        <eightbitlab.com.blurview.BlurView
            android:id="@+id/blurView_iv_item"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:background="@drawable/all_blur_bg"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent">

            <androidx.constraintlayout.widget.ConstraintLayout
                android:layout_width="145dp"
                android:layout_height="166dp"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toTopOf="parent">


            </androidx.constraintlayout.widget.ConstraintLayout>


        </eightbitlab.com.blurview.BlurView>

        <ImageView
            android:id="@+id/iv_participant"
            android:layout_width="145dp"
            android:layout_height="166dp"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="@+id/blurView_iv_item" />
       </androidx.constraintlayout.widget.ConstraintLayout>
    </androidx.constraintlayout.widget.ConstraintLayout>


My activity

   class PurposeMeetingActivity : AppCompatActivity() {

    lateinit var viewAdapter: ParticipantAdapter
    lateinit var  viewManager: LinearLayoutManager

    var listOfParticipant = ArrayList<Participant>()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.add_picture_recyclerview)


        blurView(blurView_iv_item)
        viewAdapter = ParticipantAdapter()
        viewManager = LinearLayoutManager(this, LinearLayoutManager.HORIZONTAL, false)

        listOfParticipant.add(Participant(R.drawable.test))
        listOfParticipant.add(Participant(R.drawable.test))
        listOfParticipant.add(Participant(R.drawable.test))
        listOfParticipant.add(Participant(R.drawable.test))

        recyclerview_add_picture.adapter = viewAdapter
        recyclerview_add_picture.layoutManager = viewManager

        viewAdapter.update(listOfParticipant)




    }


    fun blurView(view: BlurView) {
        val radius = 20f

        val decorView: View = window.decorView
        val windowBackground: Drawable = decorView.getBackground()

        view.setupWith(decorView.findViewById(android.R.id.content))
                .setFrameClearDrawable(windowBackground)
                .setBlurAlgorithm(RenderScriptBlur(this))
                .setBlurRadius(radius)
                .setBlurAutoUpdate(true)
                .setHasFixedTransformationMatrix(true)


        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            view.setOutlineProvider(ViewOutlineProvider.BACKGROUND);
            view.setClipToOutline(true)
        }

    }



}

**Comment by Dimezis** [comment]
Your crash has nothing to do with the library. 
`blurView_iv_item` does not exist in your Activity's layout so it's null and you get that error.

**Comment by Dimezis** [comment]
The idea is that you set up the BlurView in the Adapter, in each ViewHolder when it's created.
Not in Activity

**Comment by greatkub** [comment]
Thank you so much for your response. I tried to do in view holder, I can run the project but blurView doesn't work . Could you tell me more what should I do?
    
    class ParticipantAdapter: RecyclerView.Adapter<ParticipantAdapter.ViewHolder>() {

    private var listOfParticipant = ArrayList<Participant>()

    inner class ViewHolder(cellView: View): RecyclerView.ViewHolder(cellView) {
        var image_participant = cellView.iv_participant
        var blurImage = cellView.blurView_iv_item
        var constBlurImage = cellView.constraintBlurviewItem
    }

    fun update(newList: ArrayList<Participant>) {
        this.listOfParticipant = newList
        notifyDataSetChanged()
    }

    override fun getItemCount(): Int {
        return listOfParticipant.size
    }

    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): ViewHolder {
        var inflater = parent.context.getSystemService(Context.LAYOUT_INFLATER_SERVICE) as LayoutInflater
        var participantView = inflater.inflate(R.layout.add_picture_cell, parent , false)

        return ViewHolder(participantView)
    }

    override fun onBindViewHolder(holder: ViewHolder, position: Int) {
        holder.image_participant.setImageResource(listOfParticipant[position].participantImage)
        
        holder.blurImage.setupWith(holder.constBlurImage).setBlurRadius(25f)
                .setBlurEnabled(true)
                .setBlurAlgorithm(RenderScriptBlur(holder.blurImage.context))
                .setBlurRadius(25f)
                .setHasFixedTransformationMatrix(true)
                .setBlurAutoUpdate(true)
       }
    }

**Comment by Dimezis** [comment]
Any luck? Can I close the issue?

**Comment by Dimezis** [comment]
Closing due to inactivity
