### ISSUE TITLE
Calling RS with no Context active.

### ISSUE THREAD

**Issue by RickyHal** [Dimezis/BlurView#146]
I got a crash when use blurview, but I don't know how to fix it, dose anyone can help me?
Exception is:

```Java 
android.renderscript.RSInvalidStateException: Calling RS with no Context active.
    at android.renderscript.RenderScript.validate(RenderScript.java:1252)
    at android.renderscript.Allocation.createFromBitmap(Allocation.java:2798)
    at android.renderscript.Allocation.createFromBitmap(Allocation.java:3063)
    at eightbitlab.com.blurview.RenderScriptBlur.blur(RenderScriptBlur.java:47)
    at eightbitlab.com.blurview.BlockingBlurController.blurAndSave(BlockingBlurController.java:178)
    at eightbitlab.com.blurview.BlockingBlurController.updateBlur(BlockingBlurController.java:126)
    at eightbitlab.com.blurview.BlockingBlurController$1.onPreDraw(BlockingBlurController.java:56)
    at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1098)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3163)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1993)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8459)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1256)
    at android.view.Choreographer.doCallbacks(Choreographer.java:995)
    at android.view.Choreographer.doFrame(Choreographer.java:887)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1224)
    at android.os.Handler.handleCallback(Handler.java:900)
    at android.os.Handler.dispatchMessage(Handler.java:103)
    at android.os.Looper.loop(Looper.java:219)
    at android.app.ActivityThread.main(ActivityThread.java:8387)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
```

and code is 
```kotlin
   val radius = 0.5f
   val decorView: View = window.decorView
   val rootView: ViewGroup = decorView.findViewById(android.R.id.content) as ViewGroup
   val windowBackground: Drawable = decorView.background
   binding.maskView.setupWith(rootView)
            .setFrameClearDrawable(windowBackground)
            .setBlurAlgorithm(RenderScriptBlur(this))
            .setBlurRadius(radius)
            .setBlurAutoUpdate(true)
            .setHasFixedTransformationMatrix(true)
```

**Comment by Dimezis** [comment]
If you have a setup where this can be reliably reproduced, I will gladly take a look, otherwise, I don't have the slightest idea why it could be happening.
