### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by SudoDios** [Dimezis/BlurView#164]
1) Library version -> 1.6.6
2) Device and OS version -> android 11 poco x3 pro
3) Detailed steps to reproduce the issue -> 
I test blur lib and get issue when translate blurview (not update blur on new position on screen)
4) XML layout and code for BlurView setup
```xml
<androidx.coordinatorlayout.widget.CoordinatorLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <androidx.coordinatorlayout.widget.CoordinatorLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:gravity="center"
        android:background="#0C1D25"
        android:orientation="vertical">

        <androidx.appcompat.widget.AppCompatImageView
            android:id="@+id/img"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:scaleType="centerCrop"
            android:layout_gravity="center"/>

        <com.google.android.material.button.MaterialButton
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="bottom|center"
            android:layout_margin="25dp"/>

    </androidx.coordinatorlayout.widget.CoordinatorLayout>

    <eightbitlab.com.blurview.BlurView
        android:id="@+id/blurView"
        android:layout_width="200dp"
        android:layout_height="200dp"
        android:layout_gravity="center"
        app:blurOverlayColor="#00ffffff"/>

</androidx.coordinatorlayout.widget.CoordinatorLayout>
```
Backend
```kotlin
        val radius = 20f
        val decorView: View = window.decorView
        val windowBackground: Drawable = decorView.background
        binding.blurView.setupWith(decorView.findViewById(R.id.content))
            .setFrameClearDrawable(windowBackground)
            .setBlurAlgorithm(RenderScriptBlur(this))
            .setBlurRadius(radius)
            .setBlurAutoUpdate(true)
            .setHasFixedTransformationMatrix(true)

        var dX = 0f
        var dY = 0f
        binding.blurView.setOnTouchListener { v, event ->
            when (event.action) {
                MotionEvent.ACTION_DOWN -> {
                    dX = binding.blurView.x - event.rawX
                    dY = binding.blurView.y - event.rawY
                }
                MotionEvent.ACTION_MOVE -> binding.blurView.animate()
                    .x(event.rawX + dX)
                    .y(event.rawY + dY)
                    .setDuration(0)
                    .start()
            }
            true
        }
```

**Comment by Dimezis** [comment]
`.setHasFixedTransformationMatrix(true)` >  `.setHasFixedTransformationMatrix(false)`

**Comment by SudoDios** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.getLocationOnScreen(int[])' on a null object reference
        at eightbitlab.com.blurview.BlockingBlurController.setupInternalCanvasMatrix(BlockingBlurController.java:139)
        at eightbitlab.com.blurview.BlockingBlurController.updateBlur(BlockingBlurController.java:121)
        at eightbitlab.com.blurview.BlockingBlurController$1.onPreDraw(BlockingBlurController.java:56)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1093)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3238)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2075)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8512)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1076)
        at android.view.Choreographer.doCallbacks(Choreographer.java:897)
        at android.view.Choreographer.doFrame(Choreographer.java:826)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1061)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:8056)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

**Comment by SudoDios** [comment]
Thanks
