### ISSUE TITLE
Crash, Fatal Exception: java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by JustTrust** [Dimezis/BlurView#22]
Hi Dmitriy! Now I got a crash in blur view. I can't reproduce it on my devices, but it happens several time. It happened  only on Samsung SM-G900F. This is crashlytics log:

`Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=1024; index=1064
       at eightbitlab.com.blurview.StackBlur.blur(SourceFile:115)
       at eightbitlab.com.blurview.DefaultBlurController.blurAndSave(SourceFile:233)
       at eightbitlab.com.blurview.DefaultBlurController.drawBlurredContent(SourceFile:216)
       at eightbitlab.com.blurview.BlurView.draw(SourceFile:56)
       at android.view.View.getDisplayList(View.java:13397)
       at android.view.View.getDisplayList(View.java:13439)
       at android.view.View.draw(View.java:14217)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.getDisplayList(View.java:13392)
       at android.view.View.getDisplayList(View.java:13439)
       at android.view.View.draw(View.java:14217)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.draw(View.java:14503)
       at android.widget.FrameLayout.draw(FrameLayout.java:472)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2326)
       at android.view.View.getDisplayList(View.java:13397)
       at android.view.View.getDisplayList(View.java:13439)
       at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1582)
       at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1449)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2388)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2260)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1890)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1007)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5677)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
       at android.view.Choreographer.doCallbacks(Choreographer.java:574)
       at android.view.Choreographer.doFrame(Choreographer.java:544)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5021)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:827)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:643)
       at dalvik.system.NativeStart.main(NativeStart.java)`

Please look at it, maybe you have some ideas.

**Comment by Duoblood** [comment]
+ SAMSUNG-SM-N900A

**Comment by Dimezis** [comment]
Thanks, I'll try to investigate it. Can you switch for othe blur algorithm for now?

**Comment by Dimezis** [comment]
There's certainly a critical bug in StackBlur implementation.
But I'm not an author of this algorithm and don't see any obvious cause.

So, instead of wasting a time to fix this, I decided to switch to other default blur algorithm and remove this one due to its poor performance and implementation flaw.

This will be released in the next version.

**Comment by Dimezis** [comment]
Removed in 1.2.0 version
