### ISSUE TITLE
Calling RS with no Context active.

### ISSUE THREAD

**Issue by narendraanjana** [Dimezis/BlurView#222]
Please include:
1) Library version = 2.0.2
2) Device and OS version = Samsung Android 13
5) Stacktrace in case of a crash
` Fatal Exception: android.renderscript.RSInvalidStateException: Calling RS with no Context active.
       at android.renderscript.RenderScript.validate(RenderScript.java:1241)
       at android.renderscript.Allocation.createFromBitmap(Allocation.java:2798)
       at android.renderscript.Allocation.createFromBitmap(Allocation.java:3063)
       at eightbitlab.com.blurview.RenderScriptBlur.blur(RenderScriptBlur.java:57)
       at eightbitlab.com.blurview.PreDrawBlurController.blurAndSave(PreDrawBlurController.java:168)
       at eightbitlab.com.blurview.PreDrawBlurController.updateBlur(PreDrawBlurController.java:118)
       at eightbitlab.com.blurview.PreDrawBlurController$1.onPreDraw(PreDrawBlurController.java:50)
       at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1124)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3854)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2618)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9971)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010)
       at android.view.Choreographer.doCallbacks(Choreographer.java:809)
       at android.view.Choreographer.doFrame(Choreographer.java:744)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8653)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
        `

**Comment by narendraanjana** [comment]
Hi @Dimezis , is this issue fixed with latest version

**Comment by Dimezis** [comment]
It's not.
It's also (most likely) not a bug in this library - something in your app is calling `RenderScript.releaseAllContexts()`, which destroys the RS context BlurView creates for blur.

This could be Glide's fault, for example - https://github.com/wasabeef/glide-transformations/blob/d950f0c33f27f864e4ab4b26fce66c27079911c1/transformations/src/main/java/jp/wasabeef/glide/transformations/internal/RSBlur.java#L51

So if you're using Glide, that's a likely candidate.

You can work this around by implementing your own `BlurAlgorithm that delegates everything to `RenderscriptBlur`, try-catches the blur and recreates the `RenderscriptBlur` if something killed the context.

**Comment by M-Khay** [comment]
Hello Dimezis,

can you please explain this with some code. 

"you can work this around by implementing your own BlurAlgorithm that delegates everything to RenderscriptBlur, try-catches the blur and recreates the RenderscriptBlur if something killed the context."

**Comment by AyakaAgo** [comment]
> You can work this around by implementing your own `BlurAlgorithm` that delegates everything to `RenderscriptBlur`, try-catches the blur and recreates the `RenderscriptBlur` if something killed the context.

can it be implemented in the library?

like.... WeakReference the Context, and try-catch create

**Comment by Dimezis** [comment]
@AyakaAgo 
It can be, currently `RenderscriptBlur` already try-catches the blur, although it doesn't recreate the context, it will just stop blurring. 
If you want, you can make your own blur algorithm that would recreate the context and continue blurring, but I would rather advise not using Glide transformations (or forking it and stopping calling `releaseAllContexts`), otherwise recreating the context and allocations repeatedly would impact the performance.
