### ISSUE TITLE
Crash in other lib

### ISSUE THREAD

**Issue by Yuphee** [Dimezis/BlurView#40]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/com.google.android.maps.jar", zip file "/data/app/com.yr.mx-2/base.apk"],nativeLibraryDirectories=[/data/app/com.yr.mx-2/lib/arm64, /data/app/com.yr.mx-2/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]] couldn't find "libMyJni.so"
                                                               at java.lang.Runtime.loadLibrary(Runtime.java:367)
                                                               at java.lang.System.loadLibrary(System.java:1076)
                                                               at com.yr.mx.utils.JniUtils.<clinit>(JniUtils.java:8)
                                                               at com.yr.mx.MApplication.onCreate(MApplication.java:175)
                                                               at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
                                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4726)
                                                               at android.app.ActivityThread.access$1600(ActivityThread.java:153)
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1412)
                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                               at android.os.Looper.loop(Looper.java:148)
                                                               at android.app.ActivityThread.main(ActivityThread.java:5441)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)

when i add the blurview it comes anthor error what i never meet before

**Comment by Dimezis** [comment]
I believe this happened because you don't have 64 bit version of your library. Android doesn't allow using 32 and 64 bit native libs in a single project, take a look at this article: https://developer.android.com/ndk/guides/abis.html

Please confirm if this is true.

**Comment by Yuphee** [comment]
I add the arm64-v8a in my libs and fix the problem ,it may be something so lib added include arm64 when i import the BlurView,but i didn't find any so lib in your project,where it is.

**Comment by Dimezis** [comment]
It's support Renderscript lib

**Comment by Dimezis** [comment]
Please check out 1.3.3 version, support RenderScript dependency is now optional.
Default implementation of BlurAlgorithm is now no-op.

There are 2 standard algorithms right now - RenderScriptBlur (which uses native RS) and
`SupportRenderScriptBlur` - `compile 'com.eightbitlab:supportrenderscriptblur:1.0.0'`
