### ISSUE TITLE
java.lang.IllegalArgumentException: parameter must be a descendant of this view

### ISSUE THREAD

**Issue by iskandar1023** [Dimezis/BlurView#43]
I just update the lib to latest version and now setupWith is requiring ViewGroup, so i cast it to ViewGroup but it's crashing now. Do i need more than that? thanks.
`java.lang.IllegalArgumentException: parameter must be a descendant of this view
                                                       at android.view.ViewGroup.offsetRectBetweenParentAndChild(ViewGroup.java:5459)
                                                       at android.view.ViewGroup.offsetDescendantRectToMyCoords(ViewGroup.java:5388)
                                                       at eightbitlab.com.blurview.BlockingBlurController.setupInternalCanvasMatrix(BlockingBlurController.java:175)
                                                       at eightbitlab.com.blurview.BlockingBlurController.drawBlurredContent(BlockingBlurController.java:207)
                                                       at eightbitlab.com.blurview.BlurView.draw(BlurView.java:57)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:16167)
                                                       at android.view.View.draw(View.java:16951)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                       at android.view.View.draw(View.java:17188)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:16167)
                                                       at android.view.View.draw(View.java:16951)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:16162)
                                                       at android.view.View.draw(View.java:16951)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:16162)
                                                       at android.view.View.draw(View.java:16951)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                       at android.view.View.draw(View.java:17188)
                                                       at com.android.internal.policy.DecorView.draw(DecorView.java:753)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:16167)
                                                       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:648)
                                                       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:654)
                                                       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:762)
                                                       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2800)
                                                       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2608)
                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2215)
                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                       at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                       at android.os.Handler.handleCallback(Handler.java:751)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:153)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6194)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)`

**Comment by Dimezis** [comment]
Your root ViewGroup doesn't contain the BlurView.
How are you trying to use it?

**Comment by iskandar1023** [comment]
The BlurView is in separate ProgressDialog. I tried using this to getting the GroupView
`final ViewGroup rootView = (ViewGroup) decorView.findViewById(android.R.id.content);`

**Comment by iskandar1023** [comment]
well here is the current implementation in the layout https://github.com/substratum/substratum/blob/dev/app/src/main/res/layout-v3/compile_dialog_loader.xml#L30
and how the setup now https://github.com/substratum/substratum/blob/dev/app/src/main/java/projekt/substratum/tabs/Overlays.java#L1397

**Comment by Dimezis** [comment]
Ok, thanks, I'll try to sort this out soon

**Comment by Dimezis** [comment]
Please check out 1.3.3 version. 
Now BlurView properly supports your scenario.
