### ISSUE TITLE
android 8.0

### ISSUE THREAD

**Issue by zengdeping** [Dimezis/BlurView#66]
java.lang.IllegalStateException: Software rendering doesn't support hardware bitmaps
	at android.graphics.BaseCanvas.throwIfHwBitmapInSwMode(BaseCanvas.java:532)
	at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:62)
	at android.graphics.BaseCanvas.drawBitmap(BaseCanvas.java:120)
	at android.graphics.Canvas.drawBitmap(Canvas.java:1434)
	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:529)
	at android.widget.ImageView.onDraw(ImageView.java:1349)
	at android.view.View.draw(View.java:19145)
	at android.view.View.draw(View.java:19015)

**Comment by Dimezis** [comment]
Conditions?
